Pico: add some information about video
Neotron-Compute/Neotron-Book pull request #13
Opened 2022-12-29 14:33 UTC by pferreir

2022-12-29 19:01 UTC, thejpster commented on src/neotron_pico.md
>      * 640x400, 640x480 and 800x600
```suggestion
    * 640x480 @ 60 Hz (gives a 80x30 text mode)
    * 640x400 @ 70 Hz (gives a 80x25 text mode)
```

2022-12-29 19:02 UTC, thejpster requested changes
Looks great to me! A big improvement.

Just one comment suggesting the removal of the mention of 800x600 mode, as we don't support that (we'd need a 40 MHz pixel clock and to do that we probably need to overclock to 200 MHz)

2022-12-29 22:15 UTC, pferreir commented
Great! I'll try to work on a couple more sections.

2022-12-30 12:04 UTC, thejpster approved these changes

2022-12-30 12:07 UTC, merged